services:

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: korie123
      MYSQL_DATABASE: axum_rust
      MYSQL_USER: korie
      MYSQL_PASSWORD: korie123
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    restart: always

  redis:
    image: redis:7.0
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: always

volumes:
  mysql-data:

networks:
  backend:
    driver: bridge
